language : android
sudo : required
jdk : oraclejdk8
env:
 global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ADB_INSTALL_TIMEOUT=8
    - CODECOV_TOKEN="5cc7799d-9403-4fd5-a414-600033562ae9"
android :
  components :
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android - $ANDROID_API_LEVEL
    - extra-google-google_play_services
    - extra-google-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
script :
  - ./gradlew clean assembleDebug assembleRelease testDebug createDebugUnitTestCoverageReport
  # Renaming folder and files of reports so codecov.io can find it
  - mv app/build/reports/jacoco/createDebugUnitTestCoverageReport app/build/reports/jacoco/jacocoTestDebugUnitTestReport
  - mv app/build/reports/jacoco/jacocoTestDebugUnitTestReport/createDebugUnitTestCoverageReport.xml app/build/reports/jacoco/jacocoTestDebugUnitTestReport/jacocoTestDebugUnitTestReport.xml
  # Codecov.io
  - bash <(curl -s https://codecov.io/bash)
before_install:
    - yes | sdkmanager "platforms;android-28"
